package externalservice

import (
	externalservice "bnbot/app/bff/bot_register/infrastructure/external_service"
	externalbotregistertemplatcoreservice "bnbot/app/core/bot_register_template/service"
)

type botRegisterTemplateService struct {
	externalBotRegisterTemplatCoreService externalbotregistertemplatcoreservice.IBotBNTemplateService
}

func NewBotRegisterTemplateService(externalBotRegisterTemplatCoreService externalbotregistertemplatcoreservice.IBotBNTemplateService) externalservice.IBotRegisterTemplateService {
	return &botRegisterTemplateService{externalBotRegisterTemplatCoreService: externalBotRegisterTemplatCoreService}
}
